basePath: /api/v1
definitions:
  main.Publisher:
    properties:
      name:
        type: string
    type: object
  main.Subscriber:
    properties:
      name:
        type: string
    type: object
  main.publish:
    properties:
      message:
        type: string
      name:
        type: string
      topic:
        type: string
    type: object
  main.topic:
    properties:
      name:
        type: string
      subscriber:
        type: string
    type: object
info:
  contact: {}
paths:
  /messaging/publish:
    post:
      consumes:
      - application/json
      description: Pass in a topic, a publisher and a message
      parameters:
      - description: Publish object
        in: body
        name: publish
        required: true
        schema:
          $ref: '#/definitions/main.publish'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Publish a message to a topic
      tags:
      - example
  /messaging/publisher:
    post:
      consumes:
      - application/json
      description: Create a new publisher and give it a name
      parameters:
      - description: Publisher object
        in: body
        name: publisher
        required: true
        schema:
          $ref: '#/definitions/main.Publisher'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create a new publisher
      tags:
      - example
  /messaging/state:
    get:
      consumes:
      - application/json
      description: Print the nested structure of a system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Print system
      tags:
      - example
  /messaging/subscriber:
    post:
      consumes:
      - application/json
      description: Create a new subscriber with a name
      parameters:
      - description: Subscriber object
        in: body
        name: subscriber
        required: true
        schema:
          $ref: '#/definitions/main.Subscriber'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create a new subscriber
      tags:
      - example
  /messaging/topic:
    post:
      consumes:
      - application/json
      description: Create a new topic and associate it with a subscriber
      parameters:
      - description: Topic object
        in: body
        name: topic
        required: true
        schema:
          $ref: '#/definitions/main.topic'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create a new topic
      tags:
      - example
  /messaging/unsubscribe:
    put:
      consumes:
      - application/json
      description: Remove listener from subscriber to a specific topic
      parameters:
      - description: Topic object
        in: body
        name: topic
        required: true
        schema:
          $ref: '#/definitions/main.topic'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Unsubscribe subscriber to a topic
      tags:
      - example
swagger: "2.0"
